# Generated by Django 3.2.19 on 2023-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0004_auto_20230515_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='pollvoters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('restaurant', models.CharField(max_length=200, null=True)),
                ('Location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='person',
        ),
    ]
