# Generated by Django 3.2.19 on 2023-05-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_rename_poll_pollvoters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollvoters',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pollvoters',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pollvoters',
            name='restaurant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
